App_Login/urls.py
from django import views
from django.urls import URLPattern, path
from App_Login import views
app_name='App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name='sign_up'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
]

Reading_Book_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User_app.urls')),
    path('accounts/', include('App_Login.urls')),
    
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User_app/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('',views.user_list,name='user_list'),
    path('add_user',views.Add_User,name='add_user'),
    path('profile/<int:primarykey>',views.user_Profile,name='profile'),
    path('edit_user/<int:primarykey>',views.Edit_User,name='edit_user'),
    path('delete/<int:primarykey>',views.Delete_profile,name='delete_user'),

]

App_Login/models.py
from pyexpat import model
from re import M
from turtle import mode
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

User_app/models.py
from django.db import models

# Create your models here.
class User_list(models.Model):
    name=models.CharField(max_length=60)
    address=models.CharField(max_length=300)
    message=models.CharField(max_length=500)
    photo=models.ImageField(upload_to='photo',null=False,blank=False)
    def __str__(self):
        return str(self.name)

class Writer(models.Model):
    user=models.ForeignKey(User_list,on_delete=models.CASCADE,null=True,blank=True)
    writer_name=models.CharField(max_length=30)
    book_title=models.CharField(max_length=70)
    def __str__(self):
        return str(self.user)

App_Login/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class CreateNewUser(UserCreationForm):
    email=forms.EmailField(required=True,label="",
    widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username=forms.CharField(required=True,label="",
    widget=forms.TextInput(attrs={'placeholder':'username'}))
    password1=forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder':'password'})
    )
    password2=forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder':'password'})
    )
    class Meta:
        model=User
        fields=('email','username','password1','password2')

User_app/forms.py
from dataclasses import fields
from pyexpat import model
from django.forms import ModelForm
from .models import *

class ProfileForm(ModelForm):
    class Meta:
        model = Writer
        fields = ['user','writer_name','book_title']

class UserForm(ModelForm):
    class Meta:
        model=User_list
        fields=['name','address','photo','message']

App_Login/views.py
from multiprocessing import context
from multiprocessing.dummy import current_process
from urllib.request import Request
from django.shortcuts import render,HttpResponseRedirect
from App_Login.forms import *
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse,reverse_lazy
from App_Login.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.
def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method=='POST':
        form=CreateNewUser(data=request.POST)
        if form.is_valid():
            user=form.save()
            registered=True
            # user_profile=UserProfile(user=user)
            # user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    context={
        'title':'Signup',
        'form':form
    }

    return render(request,'App_Login/signup.html',context)

def login_user(request):
    form=AuthenticationForm()
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('User:user_list'))

    context={
        'title':login,
        'form':form
    }
    return render(request,'APP_Login/login.html',context)


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))

User_app/views.py
from multiprocessing import context
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
# @login_required
def user_list(request):
    users=User_list.objects.all()
    context={
        'users':users,
    }
    return render(request,'User/user.html',context)

def user_Profile(request,primarykey):
    user_details=User_list.objects.get(pk=primarykey)   
    writers=Writer.objects.all()
    for i in writers:
        if i.user.id == primarykey:
            writer_list=i
            print(writer_list)
    context={
        'user_details':user_details,
        'writer_list':writer_list
    }
    return render(request,'User/profile.html',context)

@login_required
def Edit_User(request,primarykey):
    user_details=User_list.objects.get(pk=primarykey)   
    edit_user_form =  UserForm(instance=user_details)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user_details)
        if form.is_valid():
            form.save()
            
    context={
        'edit_user_form':edit_user_form,
    }
    return render(request,'User/edit_user.html',context)

@login_required
def Add_User(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "User has been listed")
            return redirect('/')
   
    context={
        'form':form
    }
    return render(request,'User/add_user.html',context)

@login_required
def Delete_profile(request, primarykey):
    user_details=User_list.objects.get(pk=primarykey).delete()
    context = {
        'user_details' : user_details
    }
    return redirect('/',context)

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>

    .login{
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .signup{
    width: 550px;
    border: 1px solid #ccc;
    padding-top: 5px;

}
</style>
{% endblock %}
{% block body_block %}
<center>
<div class="login">   
<form action="" method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" style="width: 100%;" class="btn btn-primary">Log in</button>
</form>
</div>
<br>
<div class="signup">
    <p>Have an Account?<a href="{% url 'App_Login:sign_up' %}">Sign Up</a></p>
</div>
</center>



{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
<style>

.sign_up{
    width: 550px;
    border: 1px solid #ccc;
    padding: 40px;
}
.log_in{
    width: 550px;
    border: 1px solid #ccc;
    padding-top: 5px;

}

</style>
{% endblock %}
{% block body_block %}
<center>
<div class="sign_up">
    <h3>Sign Up Here</h3>
<form action="" method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" style="width: 100%;" class="btn btn-primary">Sign Up</button>
</form>
</div>
<br>
<div class="log_in">
<p>Have an Account?<a href="{% url 'App_Login:login' %}">Log in</a></p>
</div>
</center>
{% endblock %}

templates/User/add_user.html
{% extends 'base.html' %}
{% block body_block %}
<div>
    {% for message in messages %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
      {% endfor %}
      
    <form method="POST">
      {% csrf_token %}
      <h3 style="margin-bottom: 1.3rem">Add New User</h3>
      {% for add_user in form %}
      <div style="margin-bottom: 1rem">
        <label for="">{{ add_user.label_tag }}</label>
        {{ add_user }}
      </div>
      {% endfor %}
  
      <button class="btn edit-task" type="submit">Submit</button>
      
    </form>
    <button style="margin-top: 1rem" class="btn task-view">
      <a style="color: #fff; text-decoration: none" href="{% url 'user_list' %}"
        >Back</a
      >
    </button>
  </div>
{% endblock %}

templates/User/edit_user.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %} 
<div>
    <form method="POST">
      {% csrf_token %}
      <h3 style="margin-bottom: 1.3rem">Edit User Profile</h3>
      {% for edit_field in edit_user_form %}
      <div style="margin-bottom: 1rem">
        <label for="">{{ edit_field.label_tag }}</label>
        {{ edit_field }}
      </div>
      {% endfor %}
      <button class="btn btn-info" type="submit">Submit</button>
  </form>
  <button style="margin-top: 1rem" class="btn task-view">
    <a style="color: #fff; text-decoration: none" href="{% url 'user_list' %}"
      >Back
      </a>
  </button>
</div>
{% endblock %}

templates/User/profile.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %} 
        <div class="profile">
            <img src='/media/{{ user_details.photo }}' style=" height: 40%; width:40%;" alt="Avatar" class="image" style="width:100%">
            <div class="middle"> 
              <div class="text"> 
                  {{ user_details.name }}
               </div> 
             </div>
        </div>


        <div class="details">
            <div>Writer Name: {{ writer_list.writer_name }}</div> 
            <div> Writer Book: {{ writer_list.book_title }}</div>
        
        </div>
      
</div>
{% if request.user.is_authentcated %}
<a class=" btn edit-task btn-info ml-5" href="{% url 'edit_user' primarykey=user_details.id %}"> Edit Profile</a>   
{% endif %}
{% endblock %}

templates/User/user.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

{% for user in users %}
<div class="task-table">
    <div class="task-title">
        <a href="{% url 'profile' primarykey=user.id %}">{{ user.name }}</a>
    </div>
    
    <div class="actions-btn">
        <a class="btn task-view" href="{% url 'profile' primarykey=user.id %}">View Profile</a>
        {% if request.user.is_authenticated %}
        <a class="btn btn-danger" href="{% url 'delete_user' primarykey=user.id %}">Delete</a>
        {% endif %}

        
    </div>

</div>
{% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
 <div class="containers">
        <nav>
         <div class="logo">
          <a href="{% url 'user_list' %}">Our Writer</a>
         </div>
          <ul>
          {% if request.user.is_authenticated %}
           <li><a href="{% url 'add_user' %}">Add New</a></li> 
           <li><a href="{% url 'App_Login:login' %}">Log Out</a></li>   
           {% else %}  
           <li><a href="{% url 'App_Login:login' %}">Log in</a></li> 
           {% endif %}                                
          </ul>
        </nav>
<div class="main-body">
{% block body_block %}

{% endblock %}
</div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>